#!/usr/bin/env bash

# Script to display "Best School" 10 times using a for loop

# Use the for loop to iterate 10 times
for ((i=1; i<=10; i++))
do
    # Display "Best School" in each iteration
    echo "Best School"
done
