#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with Fizz, Buzz, or FizzBuzz conditions

# Use a for loop to iterate over numbers from 1 to 100
for ((i=1; i<=100; i++))
do
    # Check conditions and display accordingly
    if ((i % 3 == 0)) && ((i % 5 == 0))
    then
        # Display FizzBuzz for multiples of 3 and 5
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        # Display Fizz for multiples of 3
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        # Display Buzz for multiples of 5
        echo "Buzz"
    else
        # Display the number for other cases
        echo $i
    fi
done
