#!/usr/bin/env bash
# This script provides information about the school file

# Specify the file name
file_name="school"

# Check if the file exists
if [ -e "$file_name" ]
then
    # File exists
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$file_name" ]
    then
        # File is not empty
        echo "school file is not empty"

        # Check if the file is a regular file
        if [ -f "$file_name" ]
        then
            # File is a regular file
            echo "school is a regular file"
        else
            # File is not a regular file
            echo "school is not a regular file"
        fi
    else
        # File is empty
        echo "school file is empty"
    fi
else
    # File does not exist
    echo "school file does not exist"
fi
