#!/usr/bin/env bash

# Bash script to connect to a server using ssh with a private key and user ubuntu

# Usage: ./connect_to_server.sh

# Set server IP address
server_ip="52.201.211.127"

# Set private key path
private_key="~/.ssh/school"

# Connect to server using ssh
ssh -i "~/.ssh/school" ubuntu@"52.201.211.127"

