#!/usr/bin/env bash
# This script generates an RSA key pair named 'school' with 4096 bits and protects it with the passphrase 'betty'

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f school -N "betty"
